Rename the fonction name to resolve the compile conflict error.
error msg:
vela/external/lz4/lz4/tests/roundTripTest.c:217: multiple definition of `bad_usage'; /home/yangjiao/0521_sim/vela/nuttx/staging/libapps.a(abiTest.c.home.yangjiao.0521_sim.vela.external.lz4_1.o):/home/yangjiao/0521_sim/vela/external/lz4/lz4/tests/abiTest.c:189: first defined here
make[1]: *** [Makefile:405：nuttx] 错误 1
make: *** [tools/Unix.mk:546：nuttx] 错误 2

neededby:4087916

Signed-off-by: yangjiao <yangjiao@xiaomi.com>